server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modulith_ecommerce
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          time-between-eviction-runs: 1000ms

  docker:
    compose:
      enabled: false
      lifecycle-management: start_only
      file: compose.yaml

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        format_sql: true
    show-sql: true

logging:
  level:
    com.dev.minn.ecommerce: DEBUG