server:
  port: 9000
  servlet:
    context-path: /v1/ecommerce-api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/modulith_ecommerce
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          time-between-eviction-runs: 1000ms

  docker:
    compose:
      enabled: false
      lifecycle-management: start_only
      file: compose.yaml

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        default_batch_fetch_size: 100
        order_updates: true
        order_inserts: true
        format_sql: true
    show-sql: true

logging:
  level:
    com.dev.minn.ecommerce: DEBUG

app:
#  keycloak:
#    client-id: modulith-ecommerce-api
#    client-secret: O5KGBbjcrzz3zTJIDhGPv07wT5dD1rbg
#
#    server-url: http://localhost:8180
#    realm: minndev
#    redirect-uri: http://localhost:3000/authenticate

  brevo:
    host: smtp-relay.brevo.com
    port: 587
    smtp-key: xsmtpsib-ea2b8502a6cf1d04d4947016fc1063b26c0b8d8e76cdbef98fe5af8d1a345ada-3vuRQPaXIOhQqR7g

  rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem

  jwt:
    access-validity: 900 # access token (15 phút)
    refresh-validity: 604800 # refresh token (7 ngày)
    issuer: "minn-dev.ecommerce.com"

  security:
    public-endpoints:
      - /auth/**
      - /public/**